version: '3'
services:
  web:
    image: eap-test
    ports:
      - 8080:8080 
      - 9990:9990
      - 9999:9999
    depends_on:
      - db
  db:
    image: postgres
    environment: 
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
    ports:
      - 5432:5432 
