FROM scottysinclair/java8

RUN apt-get update && apt-get install -y less && apt-get install -y telnet && apt-get install -y iputils-ping 

# Create a user and group used to launch processes
# The user ID 1000 is the default for the first "regular" user on Fedora/RHEL,
# so there is a high chance that this ID will be equal to the current user
# making it easier to use volumes (no permission issues)
RUN groupadd -r jboss -g 1000 && useradd -u 1000 -r -g jboss -m -d /opt/jboss -s /sbin/nologin -c "JBoss user" jboss

RUN mkdir /opt/eap7 && chmod 755 /opt/eap7

COPY eap7 /opt/eap7

RUN chown -R jboss /opt/eap7

USER jboss

ENV JBOSS_HOME /opt/eap7

RUN $JBOSS_HOME/bin/add-user.sh admin admin --silent

RUN rm -rf $JBOSS_HOME/standalone/configuration/standalone_xml_history/

ENV JAVA_OPTS="-Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=n"

EXPOSE 8080 9990 9999 8787

# Define default command.
ENTRYPOINT $JBOSS_HOME/bin/standalone.sh -b 0.0.0.0
